spring:
    datasource:
        url: "jdbc:h2:./backend_exam;AUTO_SERVER=TRUE"
        username: "root"
        password: "root"
        driverClassName: "org.h2.Driver"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.H2Dialect"
s3:
    accesskey: "hI2na8J1hHFEN7u5ijvl"
    secretkey: "sUVdSRgYfwnstqsPFh9S4gE7qVyd59BqRI4dP9LE"
    endpoint: "http://92.222.10.101:9000/"
    bucketName:
        illustrations: "examillustrations"
        photos: "examphotos"
